config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'

  get 'home/about' => 'homes#about', as: 'about'

  resources :books

  resources :users, only: [:index, :show, :edit, :update,]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, optional: true

  validates :title, presence: true
  validates :body, presence: true, length: { maximum:200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy

  validates :name, uniqueness: true, presence: true, length: { minimum: 2 , maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<div id="error_explanation">
  <% if model.errors.any? %>
    <h3><%= model.errors.count %>error prohibited this obj from being saved:</h3>
    <ul><% model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %></ul>
    <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>

      <div id="error_explanation">
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul><% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %></ul>
      <% end %>
      </div>

      <%= form_with model: @book, local:true do |f| %>

      <div class="form-group">
        <%= f.label :title, 'Title' %>
        <%= f.text_field :title, class: "form-control book_title" %>
      </div>

      <div class="form-group">
        <%= f.label :opinion, 'Opinion' %>
        <%= f.text_area :body, class: "form-control book_body" %>
      </div>

      <%= f.submit 'Update Book', class: "btn btn-success" %>

    <% end %>

    <%= link_to "Show", book_path(@book) %>
    |
    <%= link_to "Back", books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">

  <%= render 'books/error', model: @book %>

    <div class="row">

      <%= render 'users/user', user: current_user %>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <p><%= book.title %></p>
                <% end %>
              </td>
              <td>
                <p><%= book.body %></p>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

  </div>
  
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    
    <%= render 'useuser', user: @book.user %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= attachment_image_tag @book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <p><%= @book.title %></p>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success"  %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/e730a2d29a.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

          <%= link_to root_path, class: "navbar-brand" do %>
            <span>Bookers</span>
          <% end %>

          <button class="navbar-toggler">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li>
                <% if user_signed_in? %>
                  <%= link_to " Home", user_path(current_user.id), class: "fas fa-home nav-link text-light" %>
                <% else %>
                  <%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %>
                <% end %>
              </li>
              <% if user_signed_in? %>
              <li>
                <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %>
              </li>
              <li>
                <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li>
                <%= link_to " Log out", destroy_user_session_path, class: "fas fa-sign-out-alt nav-link text-light", method: :delete %>
              </li>
              <% else %>
              <li>
                <%= link_to " About", about_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <li>
                <%= link_to " Sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <li>
                <%= link_to " Log in", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
              <% end %>
            </ul>
          </div>

        </div>
      </nav>

    </header>

    <main>
      <p id="notice"><%= flash[:notice] %></p>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/_user.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image2.jpg", size: "63x63" %>

  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>Introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to(edit_user_path(user.id), {class: "btn btn-outline-secondary btn-block"}) do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  </div>

  <h2 class="mt-3">New book</h2>



  <%= form_with model: Book.new, local:true do |f| %>

    <div class="form-group">
      <%= f.label :title, 'Title' %>
      <%= f.text_field :title, class: "form-control book_title" %>
    </div>

    <div class="form-group">
      <%= f.label :opinion, 'Opinion' %>
      <%= f.text_area :body, class: "form-control book_body" %>
    </div>

    <div class="form-group">
    <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>

<% end %>

</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      
      <h2>User info</h2>

      <%= render 'books/error', model: @user %>

      <%= form_with model:@user, local:true do |f| %>

        <div class="form-group">
          <%= f.label :name, 'Name' %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>

        <div class="form-group">
          <%= f.label :image, 'Image' %>
          <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
        </div>

        <div class="form-group">
          <%= f.label :introduction, 'Introduction' %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>

        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/user', user: current_user %>
    
      <div class="col-md-8 offset-md-1">
     　  <h2>Users</h2>
  　  　  <table class="table">
          <thead>
            <tr>
              <th>Image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %></td>
              <td><%= user.name %></td>
              <td>
                <%= link_to user_path(user.id) do %>
                  <p>Show</p>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
       </table>
    </div>
 
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render 'users/user', user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40" %><br>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>

    </div>
  </div>